---
title: "Script and outputs for ABC cross-validation and empirical data prediction for the species *Euphorbia segueriana* (scripts for the remaining species are similar)."
output: html_notebook
---
From the manuscript Kirschner & Perez et al. "Congruent evolutionary responses of European steppe biota to late Quaternary climate change: insights from convolutional neural network-based demographic modeling."

### Load library and input files.
```{r}
# Load the ABC library.
library(abc)

sust<-read.table("Esegueriana/testSet_ModelPredictions.txt")
models<-scan("Esegueriana/models91315.txt")
emp<-read.table("Esegueriana/Emp_ModelPredictions.txt")
emp<-apply(emp, 2, FUN = median)
```

### Load libraries and input files.
```{r}
cv.modsel <- cv4postpr(models, sust, nval=10, tol =c(.05,.01,.005,.002,.001), method="rejection")
Rej.05<-postpr(emp, models, sust, tol = .05, method = "rejection")
summary(cv.modsel)
summary(Rej.05)
```

### Load libraries and input files.
```{r}
parameters<-read.table("Esegueriana/parameters15.txt")
colnames(parameters)=c("Theta","T1","T2","T3","Ne","NeZ","NeZLGM","NeZPl","m12_LGM","m21_LGM","m12_Pl","m21_Pl")
parameters$NeZ=parameters$NeZ*parameters$Ne
parameters$NeZLGM=parameters$NeZLGM*parameters$Ne
parameters$NeZPl=parameters$NeZPl*parameters$Ne
parameters=within(parameters,rm(Theta))

sust<-read.table("Esegueriana/testSet_ParameterPredictions.txt")
emp<-read.table("Esegueriana/Emp_ParametersPredictions.txt")
emp<-apply(emp, 2, FUN = median)

cv.parest <- cv4abc(parameters, sust, nval=10, tol =c(.05,.01,.005,.002,.001), method = "rejection")

REJ.parest.001 <- abc(emp, parameters, sust, tol = .001,method = "rejection")

summary(cv.parest)

summary(REJ.parest.001)
```


